apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume
  namespace: federation-system
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/kube/federation/etcd

