isClusterService: false
serviceType: "ClusterIP"
clusterIP: "100.64.0.100"
middleware:
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "kubernetes.local."
    endpoint: "http://etcd-cluster.foo:2379"
