apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clientConnection:
  kubeconfig: "/kube/auth/kube-proxy.kubeconfig"
mode: "iptables"
conntrack:
  maxPerCore: 0
iptables:
  masqueradeAll: true
clusterCIDR: "${POD_CIDR}"
