apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-docker-registry
  namespace: kube-system
  labels:
    k8s-app: kube-docker-registry
    version: v0
spec:
  selector:
    matchLabels:
      k8s-app: kube-docker-registry
  template:
    metadata:
      labels:
        k8s-app: kube-docker-registry
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "True"
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
      volumes:
      - name: image-store
        hostPath:
          path: /pv/kube/registry/blue
