#!/bin/bash

# Contains namespaced functions for all stages

export DOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export TPL=$DOT/templates
source $DOT/env.sh
source $DOT/lib/utils.sh

source "${DOT}/lib/vm.${VM_ENGINE}.sh"

source $DOT/lib/prepare.sh
source $DOT/lib/orchestrate.sh
source $DOT/lib/provision.sh
source $DOT/lib/post.sh
source $DOT/lib/deploy.sh


clean() {
  cluster::down
  clean::binaries
  clean::tls
  vm::clean_artefacts
}

cluster::down() {
  vm::delete_containers
  post::route_clean
}

cluster::up() {
  orchestrate
  post
}

prepare() {
  prepare::bin
  prepare::tls
  vm::prepare
}

orchestrate() {
  orchestrate::masters

  post::configure_kc
  for x in $(seq 1 12); do
    deploy::apply_addon docker-registry/docker-registry-daemonset.yaml && break;
    sleep 1
  done

  orchestrate::worker 0 &
  orchestrate::worker 1 &
  wait
}

post() {
  post::configure_kc
  post::route
}

post::route() {
  post::route_clean
  post::route_add
}

all() {
  prepare
  cluster::up
}

# Verbatim, yeah!
if [[ "-lib" != "$1" ]]; then
  $@
fi
