apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-app-pv
  labels:
    type: local
    aspect: app
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/.pv/wordpress/app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-pv
  labels:
    type: local
    aspect: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/.pv/wordpress/mysql